PUT https://transaction-splitter-app.herokuapp.com/api/users/62857e5e007a23817dc9ff3c
Content-Type: application/json

{
  "name": "Patrick",
  "username": "pinhead5",
  "friends": [
    {
      "userId": "62857dd0007a23817dc9ff34"
    }
  ]
}